version: '3.7'

services:
    # Sopivan version voi valita täältä: https://hub.docker.com/r/library/postgres/tags/
    # Ympäristömuuttujat on selitetty sivulla: https://hub.docker.com/r/library/postgres/
    postgrestestidb:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: luettelo
            POSTGRES_USER: user
            POSTGRES_DB: puhelinluettelo
        ports:
         - 5432:5432 
    #backend-docker:
    #    image: backend-docker:latest
    #    environment: 
    #        SPRING_DATASOURCE_URL: jdbc:postgresql://postgrestestidb:5432/puhelinluettelo
    #    depends_on:
    #     - postgrestestidb
    #    ports:
    #     - 8080:8080
    #front_docker:
    #    image: front_docker:latest
    #    depends_on:
    #     - backend-docker
    #    ports:
    #     - 3000:3000